name: AWS setup Workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      registry:
        description: "AWS ECR Registry"
        value: ${{ jobs.configureAWS.outputs.registry }}
  

jobs:
  configureAWS:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:

      - name: Print message - ECR_REPOSITORY_FRONTEND
        run: echo ${{ vars.ECR_REPOSITORY_FRONTEND}}

      - name: Print message - AI
        run: echo  ${{ env.AWS_REGION}}
      - name: Print message - Google
        run: echo  ${{vars.AWS_REGION}}
  
  
      - name: AWS Set up
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
