# Workflow name
name: AWS Login Workflow

# Triggers for the workflow
on:
  
  workflow_call:
    # Map the workflow outputs to job outputs
  
    outputs: 
      ecr_registry:
        description: "Shot Got Sha"
        value: ${{ steps.login-ecr.outputs.registry }}

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
  

# Jobs defined in the workflow
jobs:
  aws-setup-job:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}



    