# Workflow name
name: AWS Login Workflow

# Triggers for the workflow
on:
  
  workflow_call:
    # Map the workflow outputs to job outputs
  
    outputs: 
      ecr_registry:
        description: "Shot Got Sha"
        value: ${{ steps.login-ecr.outputs.registry }}

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
  

# Jobs defined in the workflow
jobs:

  aws-setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::myawsid:role/github-actions-ecr-push
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
      - name: Publish image to ECR
        run: |
          echo "Hello"



    