# Workflow name
name: Backend Continuous Deployment
needs: [build-and-test-1, backend-build-job]
#needs: [frontend-cd-test-and-build]

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  workflow_run:
    workflows: ["Backend Continuous Integration"]
    types:
      - completed

  # Automatic trigger on pull request event against main branch is closed /merged
  push:
   
    branches: 
      - main


env:
  
    BASE_IMAGE_NAME: "backendapp"
    AWS_REGION: ${{ vars.AWS_REGION }}
    ECR_REPOSITORY: ${{vars.ECR_REPOSITORY_FRONTEND}}
    REACT_APP_MOVIE_API_URL: $${{vars.REACT_APP_MOVIE_API_URL}}

# Jobs defined in the workflow
jobs:
  backend-test-job:
    uses: ./.github/workflows/backend-test-resuable.yaml #Invoke reusable Frontend Lint and Test workflow

  frontend-cd-build-job:

    needs: backend-test-job #dependent job
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        #Configure AWS credentials and Login to ECR
      - name: Configure AWS credentials
        id: aws-setup
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}} 
    

      - name: Build, Tag and Push image to Amazon ECR #Tag the built docker image with the git sha (use GitHub Context)
        env:
          ECR_REGISTRY: ${{steps.aws-setup.outputs.ecr_registry }}
          IMAGE_TAG: ${{env.BASE_IMAGE_NAME}}-${{ needs.backend-test-job.outputs.sha_short }}
        run: |
          cd starter/backend 
          docker build  -t $ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG . 
          docker push $ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG

          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
          echo ECR_REGISTRY=$ECR_REGISTRY >> $GITHUB_ENV


      #Deploy to EK Cluster
      - name: Deploy to EKS Cluster
        run: |
          
          aws eks update-kubeconfig --name cluster --region ${{env.AWS_REGION}}
        
          cd starter/backend/k8s
         
          kustomize edit set image frontend=$ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG

          # Apply the manifests to the cluster
          kustomize build | kubectl apply -f -