name: Reusable Backend Test Workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      sha_short:
        description: "Shot Got Sha"
        value: ${{ jobs.backend-test-job.outputs.sha_short }}
  
 #Define job
jobs:
  backend-test-job:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.github-sha.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Github Sha
        id: github-sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

     

      # Install the dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
   

      # Run Test
      - name: Run Flake8
        run: |
          flake8 .
   
