# Workflow name
name: Backend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:


  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main


# Jobs defined in the workflow
jobs:
 

  backend-test-job:
    uses: ./.github/workflows/backend-test-resuable.yaml #Invoke reusable Frontend Lint and Test workflow

  backend-build-job:

    needs: backend-test-job #dependent job
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build docker frontend image #Tag the built docker image with the git sha (use GitHub Context)
       
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{needs.backend-test-job.outputs.sha_short}}
        run: |
          cd starter/frontend 
          docker build --tag=$ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG .
     

     