# Workflow name
name: Frontend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_FRONTEND}}
  REACT_APP_MOVIE_API_URL: ${{vars.REACT_APP_MOVIE_API_URL}}
  AWS_REGION: ${{ vars.AWS_REGION}}
#Jobs defined in the workflow
jobs:
  frontend-cd-lint-and-test-job:
          uses: ./.github/workflows/frontend-lint-test-resuable.yaml
  


    
  frontend-build-job:
    runs-on: ubuntu-latest
    needs: frontend-cd-lint-and-test-job #Only run job if frondend Lint and Test pass
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      #Setup docker 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


        #Configure AWS credentials and Login to ECR
      - name: Configure AWS credentials
        id: aws-setup
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}} 

      - name: Build docker frontend image #Tag the built docker image with the git sha (use GitHub Context)
       
        env:
          
          ECR_REGISTRY: ${{steps.aws-setup.outputs.ecr_registry }}
          IMAGE_TAG: ${{needs.frontend-cd-lint-and-test-job.outputs.sha_short}}
        run: |
          cd starter/frontend 
          docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} --tag=$ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG .
     
      
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
   