# Workflow name
name: Frontend Continuous Deployment
#needs: [frontend-cd-test-and-build]

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  workflow_run:
    workflows: ["Frontend Continuous Integration"]
    types:
      - completed



  

env:
    #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    BASE_IMAGE_NAME: "frontendApp"
    AWS_REGION: ${{ vars.AWS_REGION }}
    ECR_REPOSITORY: ${{vars.ECR_REPOSITORY_FRONTEND}}
    REACT_APP_MOVIE_API_URL: $${{vars.REACT_APP_MOVIE_API_URL}}

# Jobs defined in the workflow
jobs:
  frontend-cd-lint-and-test-job:
    uses: ./.github/workflows/frontend-lint-test-resuable.yaml
  configureAWS:
        #id: aws-setup
    uses: ./.github/workflows/aws-setup.yaml
  


  
  frontend-cd-build-job:
    needs: frontend-cd-lint-and-test-job #dependent job
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    #needs: frontend-cd-lint-and-test-job #Only run job if frondend Lint and Test pass
    steps:
      #- name: AWS Setup
        #id: aws-setup
      # uses: ./.github/workflows/aws-setup.yaml
      
      
  

      #Setup docker 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build docker frontend image #Tag the built docker image with the git sha (use GitHub Context)
        #if: github.ref == 'refs/heads/main'
        env:
          ECR_REGISTRY: ${{ steps.aws-setup.outputs.ecr_registry }}
          IMAGE_TAG: ${{needs.call-frontend-cd-lint-and-test-job.outputs.sha_short}}
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} -t ${{env.BASE_IMAGE_NAME}}:latest .

        #cd starter/frontend && docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} --tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        

        
       # --tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

         #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.sha_short }} -f .

   

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          
          IMAGE_TAG: ${{env.BASE_IMAGE_NAME}} - ${{ steps.git-sha.outputs.sha_short }}
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY #Authenticate to an Amazon ECR registry
          #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.sha_short }} -f .
          #---
          #aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY #Authenticate to an Amazon ECR registry
         #docker build -t $IMAGE_TAG .
          #docker tag $IMAGE_TAG:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       
      #- name: Deploy to EKS Cluster
       # run: 