name: 'Terraform Kubernetes Deployment'
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
 

env:
  AWS_REGION:  ${{ vars.AWS_REGION }}   
  TF_ACTION_WORKING_DIR: 'setup/terraform' 

jobs:
  terraform:
    name: 'Terraform'
    defaults:
      run:
        working-directory: ${{env.TF_ACTION_WORKING_DIR}}
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    environment: development

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_ACCESS_TOKEN}}
          aws-region:  ${{env.AWS_REGION}}
          mask-aws-account-id: 'false'
        
      # Set up the specified version of Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      # Initialize your Terraform configuration
      - name: Terraform Init
        run: terraform init

      # Validate your Terraform configuration
      - name: Terraform Validate
        run: terraform validate 

      # Generate and display an execution plan
      - name: Terraform Plan
        run: terraform plan 

      # Apply the changes required to reach the desired state of the configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve 
      
